### ISSUE TITLE
When the mixture coefficients becomes all zeros

### ISSUE THREAD

**Issue by fingertap** [abriosi/gmm-mml#8]
Hi! The original paper promotes the sparsity in `α` by subtracting `N/2` from the group responsibilities. However, since the sum of `w` for all groups and all data points is `N`, it is likely that all `α_m` can be zero since the sum can be less than N/2 for all groups (unless `k=2`). I wonder how do you deal with the case when all `α_m` becomes zero?

**Comment by abriosi** [comment]
I don't know the answer, I'm sorry.
